name:                PFDS
version:             0.1.0.0
github:              "rvighne/PFDS"
license:             BSD3
author:              "Rohit Vighne"
maintainer:          "rohit.vighne@gmail.com"
copyright:           "2020 Rohit Vighne"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Education

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rvighne/PFDS#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall -Wredundant-constraints -Wno-type-defaults -Wno-orphans -Wno-tabs

library:
  source-dirs: src

executables:
  PFDS-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PFDS

tests:
  PFDS-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PFDS
    - QuickCheck
